import { useState } from 'react';
import styles from './style.module.css';
import Head from 'next/head';

const proInfoItemList = [
    { name: 'Contratar', img: './contato/contrato.png', txt: 'Estou disponivel para trabalho, caso o contratante queira marcar um entrevista, é só entrar em contato.' },
    { name: 'Site', img: './contato/site.png', txt: 'Crio sites com design amigavel e profissional, além de serem responsivos, isso é, que podem ser usados em qualquer aparelho.' },
    { name: 'Tecnologias', img: './contato/tec.png', txt: 'Trabalho com as tecnologias mais pedidas do mercado, sempre tentando manter-me atualizado com as novidades tecnologicas.' },
    { name: 'Free Lancer', img: './contato/freeLancer.png', txt: 'Tenho disponibilidade para realizar trabalhos autonomos na area de desenvolvimento de sistemas.' },
]

const Contato = () => {

    const [nome, setNome] = useState('')
    const [empresa, setEmpresa] = useState('')
    const [assunto, setAssunto] = useState('')
    const [mensagem, setMensagem] = useState('')

    return (
        <>
            <Head>
                <title>Daniel Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <div className={styles.main}>
                <div className={styles.left}>
                    <div className={styles.barraLateral}>
                        <div className={styles.proInfo}>
                            {proInfoItemList.map((item, index) => (
                                <div className={styles.proInfoItem} key={index}>
                                    <div className={styles.nameImg}>
                                        <div className={styles.proInfoTitle}>{item.name}</div>
                                        <img src={item.img} alt="" className={styles.img} />
                                    </div>
                                    <div className={styles.proInfoInfo}>{item.txt}</div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
                <div className={styles.middle}>
                    <div className={styles.contatoArea}>
                        <h2 className={styles.h2}>CONTATE-ME</h2>
                        <div className={styles.inputArea}>
                            <div className={styles.inputItem}>
                                <div className={styles.inputTitle}>Nome <span className={styles.span}>* Opcional</span></div>
                                <input type="text" className={styles.input} value={nome} placeholder='Seu nome...' onChange={(e) => setNome(e.target.value)} />
                            </div>

                            <div className={styles.inputItem}>
                                <div className={styles.inputTitle}>Empresa <span className={styles.span}>* Opcional</span></div>
                                <input type="text" className={styles.input} value={empresa} placeholder='Empresa...' onChange={(e) => setEmpresa(e.target.value)} />
                            </div>

                            <div className={styles.inputItem}>
                                <div className={styles.inputTitle}>Assunto <span className={styles.span}>* Opcional</span></div>
                                <input type="text" className={styles.input} value={assunto} placeholder='Assunto...' onChange={(e) => setAssunto(e.target.value)} />
                            </div>

                            <div className={styles.inputItem}>
                                <div className={styles.inputTitle}>Mensagem <span className={styles.span}>* Opcional</span></div>
                                <input type="text" className={styles.input} value={mensagem} placeholder='Mensagem...' onChange={(e) => setMensagem(e.target.value)} />
                            </div>
                            <a href={`mailto:daniel.santos3210@outlook.com?subject=${assunto}&body=Olá eu me chamo ${nome} falo em nome da empresa ${empresa}, ${mensagem}`} className={styles.buttonEnviar}>Contato</a>
                        </div>
                    </div>
                </div>
                <div className={styles.right}>
                    <div className={styles.barraLateral}></div>
                </div>
            </div>
        </>
    )
}

export default Contato;