import { useState } from 'react';
import styles from './style.module.css';
import projetoList from '@/utils/projects';
import Head from 'next/head';

const tecs = [
    { name: 'Todas', img: '' },
    { name: 'JavaScript', img: '' },
    { name: 'HTML5', img: '' },
    { name: 'CSS3', img: '' },
    { name: 'React.js', img: '' },
    { name: 'Next.js', img: '' },
    { name: 'MySQL', img: '' },
]


const Projetos = () => {
    const [number, setNumber] = useState(0)
    const [tec, setTec] = useState(-1)

    const [tecnologia, setTecnologia] = useState('')

    const changeTec = (i: number) => {
        { tec === i ? setTec(-1) : setTec(i) }
        { tecnologia === '' ? setTecnologia(tecs[i].name) : setTecnologia(tecs[i].name) }
    }

    return (
        <>

            <Head>
                <title>Daniel Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>

            <div className={styles.main}>
                <div className={`${styles.projetoImg} ${styles.mainDiv}`} id='proj'>
                    <div className={styles.name}>{projetoList[number].name}</div>
                    <img src={projetoList[number].imgPc} alt="" />
                    <div className={styles.projDesc}>{projetoList[number].txt1}</div>
                    <div className={styles.buttonArea}>
                        <a href={projetoList[number].link} target='_blank'><div className={styles.button}>Acessar</div></a>
                        <a href={projetoList[number].github} target='_blank'><div className={styles.button}>Repositorio</div></a>
                        <a href={projetoList[number].linkedin} target='_blank'><div className={styles.button}>Linkedin</div></a>
                    </div>
                </div>
                <div className={`${styles.tecs} ${styles.mainDiv}`}>
                    <div className={styles.title}>
                        <h2 className={styles.h2}>LISTA</h2>
                        <h3 className={styles.h3}>DE</h3>
                        <h1 className={styles.h1}>PROJETOS</h1>
                    </div>
                    <div className={styles.tecList}>
                        {tecs.map((item, index) => (
                            <div onClick={() => { changeTec(index) }} style={{ margin: '10px' }}>
                                {tec === index ?
                                    <div className={styles.eachTec} key={index} style={{ background: 'rgb(25, 151, 255)' }} onClick={() => setTec(-1)}>{item.name}</div>
                                    :
                                    <div className={styles.eachTec} key={index}>{item.name}</div>
                                }
                            </div>
                        ))}
                    </div>
                </div>
                <div className={`${styles.projetoList} ${styles.mainDiv}`}>

                    {projetoList.map((item, index) => (
                        <>
                            {item.tec.find(i => i.name === tecnologia) || tecnologia === '' || tecnologia === 'Todas' ?
                                <>
                                    {index === number ?
                                        <div className={styles.eachPro} key={index} style={{ backgroundColor: 'rgb(77, 170, 255)' }} onMouseMove={() => { setNumber(index) }} >
                                            <div className={styles.nomeProjeto}>{item.name}</div>
                                            <div className={styles.date}>{item.date}</div>
                                            <div className={styles.projTec}>
                                                {item.tec.map((item, index) => (
                                                    <img src={item.img} alt="" key={index} />
                                                ))}
                                            </div>
                                        </div>
                                        :
                                        <div className={styles.eachPro} key={index} onClick={() => { setNumber(index) }} >
                                            <a href="#proj">
                                                <div className={styles.nomeProjeto}>{item.name}</div>
                                                <div className={styles.date}>{item.date}</div>
                                                <div className={styles.projTec}>
                                                    {item.tec.map((item, index) => (
                                                        <img src={item.img} alt="" key={index} />
                                                    ))}
                                                </div>
                                            </a>
                                        </div>
                                    }
                                </>
                                :
                                ''
                            }
                        </>
                    ))}
                </div>
                <div className={styles.space}></div>
            </div>
        </>
    )
}

export default Projetos;