import MainTop from '@/components/mainTop';
import styles from './style.module.css';
import CardPro from '@/components/proCard';
import Head from 'next/head';
import profissional from '@/utils/profissional';

const Profissional = () => {
    return (
        <>

            <Head>
                <title>Daniel Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <div className={styles.main}>
                <MainTop
                    letter='Profissional'
                    text="Conheça um pouco mais sobre a minha carreira no ambito Profissional."
                    img="https://www.unit.br/hs-fs/hubfs/Mercado%20de%20trabalho%20engenheiro%20de%20computac%CC%A7a%CC%83o.jpg?width=1000&name=Mercado%20de%20trabalho%20engenheiro%20de%20computac%CC%A7a%CC%83o.jpg"
                />
                <div className={styles.content}>
                    <div className={styles.barra}>
                        <div className={styles.barraTitle}>
                            <div>Diplomas</div>
                            <div className={styles.line}></div>
                        </div>
                        <div className={styles.proList}>
                            {profissional.map((item, index) => (
                                <>
                                    {item.tipo === 'Diploma' ?
                                        <CardPro name={item.name} type={item.tipo} img={item.img} link={item.link} date={item.data} />
                                        :
                                        ''
                                    }
                                </>
                            ))}
                        </div>
                    </div>
                    <div className={styles.barra}>
                        <div className={styles.barraTitle}>
                            <div>Cursos</div>
                            <div className={styles.line}></div>
                        </div>
                        <div className={styles.proList}>
                            {profissional.map((item, index) => (
                                <>
                                    {item.tipo === 'Curso' ?
                                        <CardPro name={item.name} type={item.tipo} img={item.img} link={item.link} date={item.data} />
                                        :
                                        ''
                                    }
                                </>
                            ))}
                        </div>

                    </div>
                    <div className={styles.barra}>
                        <div className={styles.barraTitle}>
                            <div>Formação</div>
                            <div className={styles.line}></div>
                        </div>
                        <div className={styles.proList}>
                            {profissional.map((item, index) => (
                                <>
                                    {item.tipo === 'Formação' ?
                                        <CardPro name={item.name} type={item.tipo} img={item.img} link={item.link} date={item.data} />
                                        :
                                        ''
                                    }
                                </>
                            ))}
                        </div>

                    </div>
                </div>
            </div>
        </>
    )
}

export default Profissional;